# Generated by Django 4.1.7 on 2023-06-23 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plant_type",
                    models.CharField(
                        choices=[
                            ("Outdoor Plants", "Outdoor Plants"),
                            ("Indoor Plants", "Indoor Plants"),
                        ],
                        max_length=14,
                        verbose_name="Plant Type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator("^.{2,}$"),
                            django.core.validators.RegexValidator(
                                "^[A-Za-z]+$", "Plant name should contain only letters!"
                            ),
                        ],
                        verbose_name="Name",
                    ),
                ),
                ("image_url", models.URLField(verbose_name="Image Url")),
                ("description", models.TextField(verbose_name="Description")),
                ("price", models.FloatField(verbose_name="Price")),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[django.core.validators.RegexValidator("^.{2,}$")],
                        verbose_name="Username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z].*",
                                "Your name must start with a capital letter!",
                            )
                        ],
                        verbose_name="First name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z].*",
                                "Your name must start with a capital letter!",
                            )
                        ],
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "profile_picture",
                    models.URLField(
                        blank=True, null=True, verbose_name="Profile Picture"
                    ),
                ),
            ],
        ),
    ]
