# Generated by Django 4.1.7 on 2023-06-24 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FruitModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z]+$", "Fruit name should contain only letters!"
                            ),
                            django.core.validators.RegexValidator("^.{2,}$"),
                        ],
                        verbose_name="Name",
                    ),
                ),
                ("image_url", models.URLField(verbose_name="Image URL")),
                ("description", models.TextField(verbose_name="Description")),
                ("nutrition", models.TextField(blank=True, verbose_name="Nutrition")),
            ],
        ),
        migrations.CreateModel(
            name="ProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=25,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z]", "Your name must start with a letter!"
                            ),
                            django.core.validators.RegexValidator("^.{2,}$"),
                        ],
                        verbose_name="First Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=35,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z]", "Your name must start with a letter!"
                            ),
                            django.core.validators.RegexValidator("^.{1,}$"),
                        ],
                        verbose_name="Last Name",
                    ),
                ),
                ("email", models.EmailField(max_length=40, verbose_name="Email")),
                (
                    "password",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.RegexValidator("^.{8,}$")],
                        verbose_name="Password",
                    ),
                ),
                ("image_url", models.URLField(blank=True, verbose_name="Image URL")),
                (
                    "age",
                    models.IntegerField(blank=True, default=18, verbose_name="Age"),
                ),
            ],
        ),
    ]
