# Generated by Django 4.1.7 on 2023-06-24 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fruitipedia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fruitmodel",
            name="name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z]+$", "Fruit name should contain only letters!"
                    ),
                    django.core.validators.RegexValidator(
                        "^.{2,}$", "Field should contain at least 2 symbols"
                    ),
                ],
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="first_name",
            field=models.CharField(
                max_length=25,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z]", "Your name must start with a letter!"
                    ),
                    django.core.validators.RegexValidator(
                        "^.{2,}$", "Field should contain at least 2 symbols"
                    ),
                ],
                verbose_name="First Name",
            ),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="last_name",
            field=models.CharField(
                max_length=35,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z]", "Your name must start with a letter!"
                    ),
                    django.core.validators.RegexValidator(
                        "^.{1,}$", "Field should contain at least 1 symbol"
                    ),
                ],
                verbose_name="Last Name",
            ),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="password",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^.{8,}$", "Field should contain at least 8 symbols"
                    )
                ],
                verbose_name="Password",
            ),
        ),
    ]
